"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function SignupPage(){
 const router=useRouter(); const [fullName,setFullName]=useState(""); const [companyName,setCompanyName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setLoading(true);const supabase=createClient();const {data,error:err}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName,company_name:companyName}}});if(err){setError(err.message);setLoading(false);return;}if(data.session){router.push('/dashboard');router.refresh();return;}router.push('/login');}
 return <main className="grid min-h-screen lg:grid-cols-[.92fr_1.08fr]"><section className="relative hidden overflow-hidden border-r border-[#dfe7ef] bg-[#07172a] p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link href="/" className="text-2xl font-black">Fleet<span className="text-[#1188ff]">Pilot</span></Link><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-[#1188ff]">Start your control center</div><h2 className="mt-5 max-w-lg text-5xl font-black leading-[1.02] tracking-[-.05em]">Run the truck like a <span className="text-[#36d575]">business.</span></h2><p className="mt-6 max-w-md leading-7 text-[#6d7f94]">Create one account for your loads, costs, fleet, maintenance and weekly profit — shared across FleetPilot web and mobile.</p></div><div className="text-xs font-bold text-[#8da0b2]">14-day trial · No card required</div><div className="absolute -right-32 top-1/3 h-96 w-96 rounded-full bg-[#1188ff]/10 blur-[100px]"/></section><section className="flex items-center justify-center px-5 py-10"><div className="w-full max-w-[450px]"><Link href="/" className="mb-10 block text-center text-3xl font-black lg:hidden">Fleet<span className="text-[#1188ff]">Pilot</span></Link><div className="mb-8"><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#1188ff]">Create FleetPilot Account</div><h1 className="mt-3 text-4xl font-black tracking-[-.04em]">Start free</h1><p className="mt-3 text-sm text-[#6d7f94]">Use the same account later on mobile and web.</p></div><form onSubmit={submit} className="fleet-card space-y-5 rounded-[28px] p-7 sm:p-8"><Field label="Your name" value={fullName} set={setFullName} placeholder="Full name"/><Field label="Company name" value={companyName} set={setCompanyName} placeholder="Your trucking company"/><Field label="Email" type="email" value={email} set={setEmail} placeholder="you@example.com"/><Field label="Password" type="password" value={password} set={setPassword} placeholder="Create a password"/>{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}<button disabled={loading} className="w-full rounded-2xl bg-[#1188ff] px-4 py-4 text-sm font-black shadow-xl shadow-blue-500/15 hover:bg-[#0f78e9] disabled:opacity-50">{loading?'Creating account...':'Create Account →'}</button><div className="text-center text-sm text-[#7b8da2]">Already have FleetPilot? <Link href="/login" className="font-black text-[#1188ff]">Sign in</Link></div></form></div></section></main>
}
function Field({label,type='text',value,set,placeholder}:{label:string;type?:string;value:string;set:(v:string)=>void;placeholder:string}){return <label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-[.12em] text-[#7b8da2]">{label}</span><input required type={type} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full rounded-2xl border border-[#dfe7ef] bg-white px-4 py-3.5 text-[#0b1730] outline-none transition focus:border-[#1188ff] focus:ring-2 focus:ring-[#1188ff]/10"/></label>}
