const fs=require("fs"),assert=require("assert");
const globalSearch=fs.readFileSync("src/components/global-search.tsx","utf8");
const page=fs.readFileSync("src/app/documents/page.tsx","utf8");
const center=fs.readFileSync("src/app/documents/document-center.tsx","utf8");
const css=fs.readFileSync("src/app/globals.css","utf8");
assert.ok(globalSearch.includes("&focus=${encodeURIComponent(row.id)}"));
assert.ok(globalSearch.includes("#document-${encodeURIComponent(row.id)}"));
assert.ok(globalSearch.includes("jurisdiction.ilike"));
assert.ok(globalSearch.includes("document_number.ilike"));
assert.ok(page.includes("initialSearch"));
assert.ok(page.includes("initialFocus"));
assert.ok(center.includes("revealDocument"));
assert.ok(center.includes("scrollIntoView"));
assert.ok(center.includes("Matching Documents"));
assert.ok(center.includes('id={`document-${doc.id}`}'));
assert.ok(center.includes("fp-doc-row-focused"));
assert.ok(center.includes("Click a result to jump to its exact row"));
assert.ok(center.includes("fp-doc-search-status"));
assert.ok(css.includes("MileVoxa Document Search Navigation v4.3.77"));
console.log("documents-search-navigation checks passed");
