const fs=require('fs');
const assert=require('assert');
const shell=fs.readFileSync('src/components/app-shell.tsx','utf8');
const css=fs.readFileSync('src/app/globals.css','utf8');
assert.ok(shell.includes('mv-app-content'));
assert.ok(shell.includes('fp-app-header'));
assert.ok(shell.includes('fp-desktop-global-search'));
assert.ok(shell.includes('fp-header-account-copy'));
assert.ok(css.includes('MileVoxa Fluid App Layout v4.3.33'));
assert.ok(css.includes('container-name:mv-app'));
assert.ok(css.includes('@container mv-app (max-width:1320px)'));
assert.ok(css.includes('@container mv-app (max-width:1120px)'));
assert.ok(css.includes('@container mv-app (max-width:930px)'));
assert.ok(css.includes('@container mv-app (max-width:720px)'));
assert.ok(css.includes('grid-template-columns:40px minmax(0,1fr) 82px!important'));
assert.ok(css.includes('overflow-x:auto!important'));
console.log('fluid-app-layout checks passed');
