const fs=require("fs");
const assert=require("assert");
const pricing=fs.readFileSync("src/app/pricing/page.tsx","utf8");
const plans=fs.readFileSync("src/app/pricing/pricing-plans.tsx","utf8");
const header=fs.readFileSync("src/components/public-header.tsx","utf8");
const css=fs.readFileSync("src/app/globals.css","utf8");
assert.ok(pricing.includes("Free access while we build MileVoxa with truckers."));
assert.ok(plans.includes("Free Beta Access"));
assert.ok(plans.includes("futurePaidPlanConfiguration"));
assert.ok(header.includes("Join the Free Beta"));
assert.ok(css.includes(".mv-beta-pricing-notice"));
assert.ok(css.includes("#16853B"));
console.log("pricing-visual-contract checks passed");
