const fs=require("fs");
const assert=require("assert");

const page=fs.readFileSync("src/app/reports/page.tsx","utf8");
const actions=fs.readFileSync("src/app/reports/report-actions.tsx","utf8");
const settlement=fs.readFileSync(
  "src/app/settlement/settlement-quick-actions.tsx",
  "utf8"
);
const css=fs.readFileSync("src/app/globals.css","utf8");

assert.ok(page.includes("companyName={companyName}"));
assert.ok(actions.includes("function exportPdf()"));
assert.ok(actions.includes("buildReportPdfLines"));
assert.ok(actions.includes("buildSimplePdf"));
assert.ok(actions.includes("MILEVOXA BUSINESS REPORT"));
assert.ok(actions.includes("BUSINESS SUMMARY"));
assert.ok(actions.includes("DAY-BY-DAY BUSINESS ACTIVITY"));
assert.ok(actions.includes("TRUCK PERFORMANCE"));
assert.ok(actions.includes("Generated by MileVoxa"));
assert.ok(actions.includes("anchor.download = `milevoxa-business-report-"));
assert.ok(actions.includes("Preparing PDF..."));
assert.ok(actions.includes('type: "application/pdf"'));

assert.ok(settlement.includes("function buildSimplePdf"));
assert.ok(settlement.includes("MILEVOXA WEEKLY SETTLEMENT"));

assert.ok(css.includes("MileVoxa Reports Settlement-Style PDF Export v4.3.60"));

console.log("reports-settlement-style-pdf checks passed");
